//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequerimientosSPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sps()
        {
            this.tarea = new HashSet<tarea>();
        }
    
        public int Id { get; set; }
        public string vuser { get; set; }
        public string referencia { get; set; }
        public string tipo { get; set; }
        public string caratula { get; set; }
        public System.DateTime fechaOrigen { get; set; }
        public System.DateTime fechaComunicada { get; set; }
        public Nullable<int> impuesto_Id { get; set; }
        public int estadoSps_Id { get; set; }
        public Nullable<int> informacionAdicional_Id { get; set; }
        public Nullable<int> clase_Id { get; set; }
        public Nullable<int> area_Id { get; set; }
        public Nullable<int> analista_Id { get; set; }
        public int origen_id { get; set; }
        public Nullable<int> severidad_id { get; set; }
        public Nullable<int> prioridad_id { get; set; }
    
        public virtual analista analista { get; set; }
        public virtual area area { get; set; }
        public virtual clase clase { get; set; }
        public virtual estadoSps estadoSps { get; set; }
        public virtual impuesto impuesto { get; set; }
        public virtual informacionAdicional informacionAdicional { get; set; }
        public virtual origen origen { get; set; }
        public virtual prioridad prioridad { get; set; }
        public virtual severidad severidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarea> tarea { get; set; }
    }
}
