//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequerimientosSPS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class spsrequerimientosEntities : DbContext
    {
        public spsrequerimientosEntities()
            : base("name=spsrequerimientosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analista> analista { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<areaTarea> areaTarea { get; set; }
        public virtual DbSet<clase> clase { get; set; }
        public virtual DbSet<equipo> equipo { get; set; }
        public virtual DbSet<estadoSps> estadoSps { get; set; }
        public virtual DbSet<estadoSpsAdicional> estadoSpsAdicional { get; set; }
        public virtual DbSet<estadoTarea> estadoTarea { get; set; }
        public virtual DbSet<impuesto> impuesto { get; set; }
        public virtual DbSet<informacionAdicional> informacionAdicional { get; set; }
        public virtual DbSet<origen> origen { get; set; }
        public virtual DbSet<prioridad> prioridad { get; set; }
        public virtual DbSet<severidad> severidad { get; set; }
        public virtual DbSet<sps> sps { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tarea> tarea { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
