//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequerimientosSPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarea()
        {
            this.areaTarea = new HashSet<areaTarea>();
        }
    
        public int Id { get; set; }
        public string vuser { get; set; }
        public string referencia { get; set; }
        public int area_Id { get; set; }
        public int analista_Id { get; set; }
        public int usuario_Id { get; set; }
        public int equipo_Id { get; set; }
        public int estadoTarea_Id { get; set; }
        public int sps_Id { get; set; }
    
        public virtual analista analista { get; set; }
        public virtual area area { get; set; }
        public virtual equipo equipo { get; set; }
        public virtual estadoTarea estadoTarea { get; set; }
        public virtual sps sps { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<areaTarea> areaTarea { get; set; }
    }
}
